version: 0.0
s: linux
files:
  - source: /
    destination: /home/ubuntu/aws-codedeploy
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: scripts/relad-pm2.sh
      timeout: 300
      runas: ubuntu